// <auto-generated />
using Catalog.PersistenceDB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Catalog.PersistenceDB.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20220222040314_Initiliaze")]
    partial class Initiliaze
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Catalog.Domain.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(100) CHARACTER SET utf8mb4")
                        .HasMaxLength(100);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Descripción del producto 1",
                            Name = "Producto 1",
                            Price = 434m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Descripción del producto 2",
                            Name = "Producto 2",
                            Price = 155m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Descripción del producto 3",
                            Name = "Producto 3",
                            Price = 252m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Descripción del producto 4",
                            Name = "Producto 4",
                            Price = 267m
                        },
                        new
                        {
                            Id = 5,
                            Description = "Descripción del producto 5",
                            Name = "Producto 5",
                            Price = 689m
                        },
                        new
                        {
                            Id = 6,
                            Description = "Descripción del producto 6",
                            Name = "Producto 6",
                            Price = 549m
                        },
                        new
                        {
                            Id = 7,
                            Description = "Descripción del producto 7",
                            Name = "Producto 7",
                            Price = 468m
                        },
                        new
                        {
                            Id = 8,
                            Description = "Descripción del producto 8",
                            Name = "Producto 8",
                            Price = 375m
                        },
                        new
                        {
                            Id = 9,
                            Description = "Descripción del producto 9",
                            Name = "Producto 9",
                            Price = 160m
                        },
                        new
                        {
                            Id = 10,
                            Description = "Descripción del producto 10",
                            Name = "Producto 10",
                            Price = 139m
                        },
                        new
                        {
                            Id = 11,
                            Description = "Descripción del producto 11",
                            Name = "Producto 11",
                            Price = 944m
                        },
                        new
                        {
                            Id = 12,
                            Description = "Descripción del producto 12",
                            Name = "Producto 12",
                            Price = 842m
                        },
                        new
                        {
                            Id = 13,
                            Description = "Descripción del producto 13",
                            Name = "Producto 13",
                            Price = 934m
                        },
                        new
                        {
                            Id = 14,
                            Description = "Descripción del producto 14",
                            Name = "Producto 14",
                            Price = 986m
                        },
                        new
                        {
                            Id = 15,
                            Description = "Descripción del producto 15",
                            Name = "Producto 15",
                            Price = 456m
                        },
                        new
                        {
                            Id = 16,
                            Description = "Descripción del producto 16",
                            Name = "Producto 16",
                            Price = 309m
                        },
                        new
                        {
                            Id = 17,
                            Description = "Descripción del producto 17",
                            Name = "Producto 17",
                            Price = 409m
                        },
                        new
                        {
                            Id = 18,
                            Description = "Descripción del producto 18",
                            Name = "Producto 18",
                            Price = 464m
                        },
                        new
                        {
                            Id = 19,
                            Description = "Descripción del producto 19",
                            Name = "Producto 19",
                            Price = 987m
                        },
                        new
                        {
                            Id = 20,
                            Description = "Descripción del producto 20",
                            Name = "Producto 20",
                            Price = 605m
                        },
                        new
                        {
                            Id = 21,
                            Description = "Descripción del producto 21",
                            Name = "Producto 21",
                            Price = 673m
                        },
                        new
                        {
                            Id = 22,
                            Description = "Descripción del producto 22",
                            Name = "Producto 22",
                            Price = 495m
                        },
                        new
                        {
                            Id = 23,
                            Description = "Descripción del producto 23",
                            Name = "Producto 23",
                            Price = 392m
                        },
                        new
                        {
                            Id = 24,
                            Description = "Descripción del producto 24",
                            Name = "Producto 24",
                            Price = 319m
                        },
                        new
                        {
                            Id = 25,
                            Description = "Descripción del producto 25",
                            Name = "Producto 25",
                            Price = 515m
                        },
                        new
                        {
                            Id = 26,
                            Description = "Descripción del producto 26",
                            Name = "Producto 26",
                            Price = 268m
                        },
                        new
                        {
                            Id = 27,
                            Description = "Descripción del producto 27",
                            Name = "Producto 27",
                            Price = 983m
                        },
                        new
                        {
                            Id = 28,
                            Description = "Descripción del producto 28",
                            Name = "Producto 28",
                            Price = 390m
                        },
                        new
                        {
                            Id = 29,
                            Description = "Descripción del producto 29",
                            Name = "Producto 29",
                            Price = 532m
                        },
                        new
                        {
                            Id = 30,
                            Description = "Descripción del producto 30",
                            Name = "Producto 30",
                            Price = 673m
                        },
                        new
                        {
                            Id = 31,
                            Description = "Descripción del producto 31",
                            Name = "Producto 31",
                            Price = 972m
                        },
                        new
                        {
                            Id = 32,
                            Description = "Descripción del producto 32",
                            Name = "Producto 32",
                            Price = 313m
                        },
                        new
                        {
                            Id = 33,
                            Description = "Descripción del producto 33",
                            Name = "Producto 33",
                            Price = 977m
                        },
                        new
                        {
                            Id = 34,
                            Description = "Descripción del producto 34",
                            Name = "Producto 34",
                            Price = 962m
                        },
                        new
                        {
                            Id = 35,
                            Description = "Descripción del producto 35",
                            Name = "Producto 35",
                            Price = 152m
                        },
                        new
                        {
                            Id = 36,
                            Description = "Descripción del producto 36",
                            Name = "Producto 36",
                            Price = 410m
                        },
                        new
                        {
                            Id = 37,
                            Description = "Descripción del producto 37",
                            Name = "Producto 37",
                            Price = 239m
                        },
                        new
                        {
                            Id = 38,
                            Description = "Descripción del producto 38",
                            Name = "Producto 38",
                            Price = 922m
                        },
                        new
                        {
                            Id = 39,
                            Description = "Descripción del producto 39",
                            Name = "Producto 39",
                            Price = 860m
                        },
                        new
                        {
                            Id = 40,
                            Description = "Descripción del producto 40",
                            Name = "Producto 40",
                            Price = 108m
                        },
                        new
                        {
                            Id = 41,
                            Description = "Descripción del producto 41",
                            Name = "Producto 41",
                            Price = 197m
                        },
                        new
                        {
                            Id = 42,
                            Description = "Descripción del producto 42",
                            Name = "Producto 42",
                            Price = 858m
                        },
                        new
                        {
                            Id = 43,
                            Description = "Descripción del producto 43",
                            Name = "Producto 43",
                            Price = 849m
                        },
                        new
                        {
                            Id = 44,
                            Description = "Descripción del producto 44",
                            Name = "Producto 44",
                            Price = 343m
                        },
                        new
                        {
                            Id = 45,
                            Description = "Descripción del producto 45",
                            Name = "Producto 45",
                            Price = 977m
                        },
                        new
                        {
                            Id = 46,
                            Description = "Descripción del producto 46",
                            Name = "Producto 46",
                            Price = 216m
                        },
                        new
                        {
                            Id = 47,
                            Description = "Descripción del producto 47",
                            Name = "Producto 47",
                            Price = 411m
                        },
                        new
                        {
                            Id = 48,
                            Description = "Descripción del producto 48",
                            Name = "Producto 48",
                            Price = 749m
                        },
                        new
                        {
                            Id = 49,
                            Description = "Descripción del producto 49",
                            Name = "Producto 49",
                            Price = 615m
                        },
                        new
                        {
                            Id = 50,
                            Description = "Descripción del producto 50",
                            Name = "Producto 50",
                            Price = 360m
                        },
                        new
                        {
                            Id = 51,
                            Description = "Descripción del producto 51",
                            Name = "Producto 51",
                            Price = 907m
                        },
                        new
                        {
                            Id = 52,
                            Description = "Descripción del producto 52",
                            Name = "Producto 52",
                            Price = 724m
                        },
                        new
                        {
                            Id = 53,
                            Description = "Descripción del producto 53",
                            Name = "Producto 53",
                            Price = 505m
                        },
                        new
                        {
                            Id = 54,
                            Description = "Descripción del producto 54",
                            Name = "Producto 54",
                            Price = 693m
                        },
                        new
                        {
                            Id = 55,
                            Description = "Descripción del producto 55",
                            Name = "Producto 55",
                            Price = 993m
                        },
                        new
                        {
                            Id = 56,
                            Description = "Descripción del producto 56",
                            Name = "Producto 56",
                            Price = 938m
                        },
                        new
                        {
                            Id = 57,
                            Description = "Descripción del producto 57",
                            Name = "Producto 57",
                            Price = 762m
                        },
                        new
                        {
                            Id = 58,
                            Description = "Descripción del producto 58",
                            Name = "Producto 58",
                            Price = 932m
                        },
                        new
                        {
                            Id = 59,
                            Description = "Descripción del producto 59",
                            Name = "Producto 59",
                            Price = 751m
                        },
                        new
                        {
                            Id = 60,
                            Description = "Descripción del producto 60",
                            Name = "Producto 60",
                            Price = 520m
                        },
                        new
                        {
                            Id = 61,
                            Description = "Descripción del producto 61",
                            Name = "Producto 61",
                            Price = 565m
                        },
                        new
                        {
                            Id = 62,
                            Description = "Descripción del producto 62",
                            Name = "Producto 62",
                            Price = 178m
                        },
                        new
                        {
                            Id = 63,
                            Description = "Descripción del producto 63",
                            Name = "Producto 63",
                            Price = 843m
                        },
                        new
                        {
                            Id = 64,
                            Description = "Descripción del producto 64",
                            Name = "Producto 64",
                            Price = 486m
                        },
                        new
                        {
                            Id = 65,
                            Description = "Descripción del producto 65",
                            Name = "Producto 65",
                            Price = 166m
                        },
                        new
                        {
                            Id = 66,
                            Description = "Descripción del producto 66",
                            Name = "Producto 66",
                            Price = 731m
                        },
                        new
                        {
                            Id = 67,
                            Description = "Descripción del producto 67",
                            Name = "Producto 67",
                            Price = 864m
                        },
                        new
                        {
                            Id = 68,
                            Description = "Descripción del producto 68",
                            Name = "Producto 68",
                            Price = 971m
                        },
                        new
                        {
                            Id = 69,
                            Description = "Descripción del producto 69",
                            Name = "Producto 69",
                            Price = 934m
                        },
                        new
                        {
                            Id = 70,
                            Description = "Descripción del producto 70",
                            Name = "Producto 70",
                            Price = 146m
                        },
                        new
                        {
                            Id = 71,
                            Description = "Descripción del producto 71",
                            Name = "Producto 71",
                            Price = 169m
                        },
                        new
                        {
                            Id = 72,
                            Description = "Descripción del producto 72",
                            Name = "Producto 72",
                            Price = 486m
                        },
                        new
                        {
                            Id = 73,
                            Description = "Descripción del producto 73",
                            Name = "Producto 73",
                            Price = 603m
                        },
                        new
                        {
                            Id = 74,
                            Description = "Descripción del producto 74",
                            Name = "Producto 74",
                            Price = 978m
                        },
                        new
                        {
                            Id = 75,
                            Description = "Descripción del producto 75",
                            Name = "Producto 75",
                            Price = 507m
                        },
                        new
                        {
                            Id = 76,
                            Description = "Descripción del producto 76",
                            Name = "Producto 76",
                            Price = 815m
                        },
                        new
                        {
                            Id = 77,
                            Description = "Descripción del producto 77",
                            Name = "Producto 77",
                            Price = 646m
                        },
                        new
                        {
                            Id = 78,
                            Description = "Descripción del producto 78",
                            Name = "Producto 78",
                            Price = 149m
                        },
                        new
                        {
                            Id = 79,
                            Description = "Descripción del producto 79",
                            Name = "Producto 79",
                            Price = 341m
                        },
                        new
                        {
                            Id = 80,
                            Description = "Descripción del producto 80",
                            Name = "Producto 80",
                            Price = 399m
                        },
                        new
                        {
                            Id = 81,
                            Description = "Descripción del producto 81",
                            Name = "Producto 81",
                            Price = 856m
                        },
                        new
                        {
                            Id = 82,
                            Description = "Descripción del producto 82",
                            Name = "Producto 82",
                            Price = 334m
                        },
                        new
                        {
                            Id = 83,
                            Description = "Descripción del producto 83",
                            Name = "Producto 83",
                            Price = 774m
                        },
                        new
                        {
                            Id = 84,
                            Description = "Descripción del producto 84",
                            Name = "Producto 84",
                            Price = 271m
                        },
                        new
                        {
                            Id = 85,
                            Description = "Descripción del producto 85",
                            Name = "Producto 85",
                            Price = 766m
                        },
                        new
                        {
                            Id = 86,
                            Description = "Descripción del producto 86",
                            Name = "Producto 86",
                            Price = 348m
                        },
                        new
                        {
                            Id = 87,
                            Description = "Descripción del producto 87",
                            Name = "Producto 87",
                            Price = 808m
                        },
                        new
                        {
                            Id = 88,
                            Description = "Descripción del producto 88",
                            Name = "Producto 88",
                            Price = 383m
                        },
                        new
                        {
                            Id = 89,
                            Description = "Descripción del producto 89",
                            Name = "Producto 89",
                            Price = 969m
                        },
                        new
                        {
                            Id = 90,
                            Description = "Descripción del producto 90",
                            Name = "Producto 90",
                            Price = 213m
                        },
                        new
                        {
                            Id = 91,
                            Description = "Descripción del producto 91",
                            Name = "Producto 91",
                            Price = 647m
                        },
                        new
                        {
                            Id = 92,
                            Description = "Descripción del producto 92",
                            Name = "Producto 92",
                            Price = 306m
                        },
                        new
                        {
                            Id = 93,
                            Description = "Descripción del producto 93",
                            Name = "Producto 93",
                            Price = 270m
                        },
                        new
                        {
                            Id = 94,
                            Description = "Descripción del producto 94",
                            Name = "Producto 94",
                            Price = 439m
                        },
                        new
                        {
                            Id = 95,
                            Description = "Descripción del producto 95",
                            Name = "Producto 95",
                            Price = 543m
                        },
                        new
                        {
                            Id = 96,
                            Description = "Descripción del producto 96",
                            Name = "Producto 96",
                            Price = 119m
                        },
                        new
                        {
                            Id = 97,
                            Description = "Descripción del producto 97",
                            Name = "Producto 97",
                            Price = 114m
                        },
                        new
                        {
                            Id = 98,
                            Description = "Descripción del producto 98",
                            Name = "Producto 98",
                            Price = 462m
                        },
                        new
                        {
                            Id = 99,
                            Description = "Descripción del producto 99",
                            Name = "Producto 99",
                            Price = 277m
                        },
                        new
                        {
                            Id = 100,
                            Description = "Descripción del producto 100",
                            Name = "Producto 100",
                            Price = 346m
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.Property<int>("ProductInStockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("ProductInStockId");

                    b.HasIndex("ProductId")
                        .IsUnique();

                    b.HasIndex("ProductInStockId");

                    b.ToTable("Stocks");

                    b.HasData(
                        new
                        {
                            ProductInStockId = 1,
                            ProductId = 1,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 2,
                            ProductId = 2,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 3,
                            ProductId = 3,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 4,
                            ProductId = 4,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 5,
                            ProductId = 5,
                            Stock = 4
                        },
                        new
                        {
                            ProductInStockId = 6,
                            ProductId = 6,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 7,
                            ProductId = 7,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 8,
                            ProductId = 8,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 9,
                            ProductId = 9,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 10,
                            ProductId = 10,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 11,
                            ProductId = 11,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 12,
                            ProductId = 12,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 13,
                            ProductId = 13,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 14,
                            ProductId = 14,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 15,
                            ProductId = 15,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 16,
                            ProductId = 16,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 17,
                            ProductId = 17,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 18,
                            ProductId = 18,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 19,
                            ProductId = 19,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 20,
                            ProductId = 20,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 21,
                            ProductId = 21,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 22,
                            ProductId = 22,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 23,
                            ProductId = 23,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 24,
                            ProductId = 24,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 25,
                            ProductId = 25,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 26,
                            ProductId = 26,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 27,
                            ProductId = 27,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 28,
                            ProductId = 28,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 29,
                            ProductId = 29,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 30,
                            ProductId = 30,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 31,
                            ProductId = 31,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 32,
                            ProductId = 32,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 33,
                            ProductId = 33,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 34,
                            ProductId = 34,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 35,
                            ProductId = 35,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 36,
                            ProductId = 36,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 37,
                            ProductId = 37,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 38,
                            ProductId = 38,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 39,
                            ProductId = 39,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 40,
                            ProductId = 40,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 41,
                            ProductId = 41,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 42,
                            ProductId = 42,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 43,
                            ProductId = 43,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 44,
                            ProductId = 44,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 45,
                            ProductId = 45,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 46,
                            ProductId = 46,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 47,
                            ProductId = 47,
                            Stock = 0
                        },
                        new
                        {
                            ProductInStockId = 48,
                            ProductId = 48,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 49,
                            ProductId = 49,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 50,
                            ProductId = 50,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 51,
                            ProductId = 51,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 52,
                            ProductId = 52,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 53,
                            ProductId = 53,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 54,
                            ProductId = 54,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 55,
                            ProductId = 55,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 56,
                            ProductId = 56,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 57,
                            ProductId = 57,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 58,
                            ProductId = 58,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 59,
                            ProductId = 59,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 60,
                            ProductId = 60,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 61,
                            ProductId = 61,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 62,
                            ProductId = 62,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 63,
                            ProductId = 63,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 64,
                            ProductId = 64,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 65,
                            ProductId = 65,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 66,
                            ProductId = 66,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 67,
                            ProductId = 67,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 68,
                            ProductId = 68,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 69,
                            ProductId = 69,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 70,
                            ProductId = 70,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 71,
                            ProductId = 71,
                            Stock = 9
                        },
                        new
                        {
                            ProductInStockId = 72,
                            ProductId = 72,
                            Stock = 17
                        },
                        new
                        {
                            ProductInStockId = 73,
                            ProductId = 73,
                            Stock = 19
                        },
                        new
                        {
                            ProductInStockId = 74,
                            ProductId = 74,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 75,
                            ProductId = 75,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 76,
                            ProductId = 76,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 77,
                            ProductId = 77,
                            Stock = 13
                        },
                        new
                        {
                            ProductInStockId = 78,
                            ProductId = 78,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 79,
                            ProductId = 79,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 80,
                            ProductId = 80,
                            Stock = 2
                        },
                        new
                        {
                            ProductInStockId = 81,
                            ProductId = 81,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 82,
                            ProductId = 82,
                            Stock = 12
                        },
                        new
                        {
                            ProductInStockId = 83,
                            ProductId = 83,
                            Stock = 15
                        },
                        new
                        {
                            ProductInStockId = 84,
                            ProductId = 84,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 85,
                            ProductId = 85,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 86,
                            ProductId = 86,
                            Stock = 11
                        },
                        new
                        {
                            ProductInStockId = 87,
                            ProductId = 87,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 88,
                            ProductId = 88,
                            Stock = 6
                        },
                        new
                        {
                            ProductInStockId = 89,
                            ProductId = 89,
                            Stock = 10
                        },
                        new
                        {
                            ProductInStockId = 90,
                            ProductId = 90,
                            Stock = 14
                        },
                        new
                        {
                            ProductInStockId = 91,
                            ProductId = 91,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 92,
                            ProductId = 92,
                            Stock = 7
                        },
                        new
                        {
                            ProductInStockId = 93,
                            ProductId = 93,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 94,
                            ProductId = 94,
                            Stock = 16
                        },
                        new
                        {
                            ProductInStockId = 95,
                            ProductId = 95,
                            Stock = 5
                        },
                        new
                        {
                            ProductInStockId = 96,
                            ProductId = 96,
                            Stock = 8
                        },
                        new
                        {
                            ProductInStockId = 97,
                            ProductId = 97,
                            Stock = 1
                        },
                        new
                        {
                            ProductInStockId = 98,
                            ProductId = 98,
                            Stock = 3
                        },
                        new
                        {
                            ProductInStockId = 99,
                            ProductId = 99,
                            Stock = 18
                        },
                        new
                        {
                            ProductInStockId = 100,
                            ProductId = 100,
                            Stock = 18
                        });
                });

            modelBuilder.Entity("Catalog.Domain.ProductInStock", b =>
                {
                    b.HasOne("Catalog.Domain.Product", null)
                        .WithOne("Stock")
                        .HasForeignKey("Catalog.Domain.ProductInStock", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
